[versions]
changelog = "2.5.0"
commonsCollection4 = "4.5.0"
gradleIntelliJPlugin = "2.10.5"
kotestAssertions = "6.0.7"
kotestRunner = "6.0.7"
kotlin = "2.2.21"
ktlint = "14.0.1"
mockk = "1.14.7"
versionCatalogUpdate = "1.0.1"
versions = "0.53.0"

[libraries]
commonsCollection4 = { module = "org.apache.commons:commons-collections4", version.ref = "commonsCollection4" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestAssertions" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotestRunner" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
# Changelog update gradle plugin - https://github.com/JetBrains/gradle-changelog-plugin
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
# IntelliJ gradle plugin - https://plugins.gradle.org/plugin/org.jetbrains.intellij
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
# Kotlin gradle plugin - https://plugins.gradle.org/plugin/org.jetbrains.kotlin.jvm
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
# ktlint formatter and linter - https://github.com/JLLeitschuh/ktlint-gradle
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
# Updates gradle plugin versions - https://github.com/littlerobots/version-catalog-update-plugin
versionCatalogUpdate = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdate" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
